<template>
   <div class="login-form">
<div>
    <h1 style="margin:3.2pt 79.85pt 0pt; text-align:center; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">AVISO DE PRIVACIDAD</span></h1>
    <p style="margin:1.1pt 79.85pt 0pt 108pt; text-indent:-28.05pt; text-align:center; line-height:111%; widows:0; orphans:0; font-size:11pt;"><strong><span style="font-family:Arial; font-size:9pt;"> USUARIOS DEL SITIO</span></strong><span style="font-family:Arial;">&nbsp;[&hellip;]</span><strong><span style="font-family:Arial; font-size:9pt; color:#1155cc;">&nbsp;</span></strong></p>
    <p style="margin:1.1pt 79.85pt 0pt 79.95pt; text-align:center; line-height:111%; widows:0; orphans:0; font-size:9pt;"><strong><span style="font-family:Arial;">ROPIEDAD BLOOD BANK</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:0pt; widows:0; orphans:0; font-size:10pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; widows:0; orphans:0; font-size:9.5pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
    <p style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><strong><span style="font-family:Arial;">Estimado Usuario:</span></strong></p>
    <p style="margin-top:0.5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
    <p style="margin:0pt 17.7pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">En  lo dispuesto  la Ley de Protecci&oacute;n de Datos Personales en Posesi&oacute;n de  Particulares  &ldquo;Ley&rdquo;), publicada en el Diario de la Federaci&oacute;n, su Reglamento, y los lineamientos y criterios aplicables, hacemos de  conocimiento el siguiente Aviso Privacidad.</span></p>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">1.- Y DOMICILIO DEL RESPONSABLE.</span></h1>
    <p style="margin:1.1pt 8.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">Banco de Sangre (&ldquo;Blood Bank&rdquo;) es  empresa constituida de con    M&eacute;xico, con domicilio en [&hellip; ] y correo electr&oacute;nico para fines de contacto:&nbsp;</span><span style="font-family:Arial; color:#1155cc;">[&hellip;]&nbsp;</span><span style="font-family:Arial;">(el &ldquo; Electr&oacute;nico&rdquo;).</span></p>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">2.- DEFINICIONES</span></h1>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
    <p style="margin-top:0.05pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><strong><span style="font-family:Arial;">Sitio</span></strong><span style="font-family:Arial;">:   de de Blood Bank&nbsp;</span><u><span style="font-family:Arial; color:#1155cc;">[&hellip;].</span></u></p>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 7.25pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><strong><span style="font-family:Arial;">Usuarios Donantes:&nbsp;</span></strong><span style="font-family:Arial;">Los usuarios del Sitio que est&aacute;n dispuestos a donar sangre de manera y no motivada por recursos econ&oacute; y/o materiales, y por lo tanto ingresan  Sitio con sus  para  contactados en caso de necesidad de donaciones.</span></p>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 27.25pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><strong><span style="font-family:Arial;">Usuarios:&nbsp;</span></strong><span style="font-family:Arial;">Los usuarios del Sitio ingresan con el fin de realizar donaciones voluntarias o altruista (Usuarios Donantes).</span></p>
    <p style="margin-top:0.5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">3.- INFORMACION</span></h1>
    <p style="margin:1.1pt 8.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">Con el prop&oacute;  documentar nuestra relaci&oacute;n  los y el proceso de conexi&oacute;n entre &eacute; y los Donantes a trav&eacute;s del Sitio, as&iacute; como para informarles sobre en los mismos, evaluar la calidad del servicio que les brindamos y cumplir con pol&iacute;ticas, procedimientos y dem&aacute;s obligaciones aplicables.</span></p>
    <p style="margin-top:0.3pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">Los datos personales que le ser&aacute;n solicitados de los Usuarios  los siguientes:</span></p>
    <p style="margin-top:0.5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-36.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">a)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Nombre completo, incluyendo apellido y</span><span style="font-family:Arial; letter-spacing:-0.05pt;">&nbsp;</span><span style="font-family:Arial;">materno</span></p>
    <p style="margin-top:1.1pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-36.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">b)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Correo electr&oacute;nico</span><span style="font-family:Arial; letter-spacing:-0.05pt;">&nbsp;</span><span style="font-family:Arial;">personal</span></p>
    <p style="margin:1.1pt 51.4pt 0pt 41.05pt; text-indent:-36pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">c)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Tipo de sangre de Usuarios Donantes</span></p>
    <p style="margin-top:0pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-36.05pt; text-align:justify; line-height:10.3pt; widows:0; orphans:0;"><span style="font-family:Arial; font-size:9pt; letter-spacing:-0.05pt;">d)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; font-size:9pt;">N&uacute;mero telef&oacute;nico de</span><span style="font-family:Arial; font-size:9pt; letter-spacing:-0.05pt;">&nbsp;</span><span style="font-family:Arial; font-size:9pt;">contacto</span></p>
    <p style="margin-top:0pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-36.05pt; text-align:justify; line-height:10.3pt; widows:0; orphans:0;"><span style="font-family:Arial; font-size:9pt; letter-spacing:-0.05pt;">e)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; font-size:9pt;">Curp</span></p>
    <p style="margin-top:0.5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 5.7pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">  no realizar&aacute; ex&aacute;menes m&eacute;dicos o pruebas  obtendr&aacute; muestras de sangre de los Usuarios, por lo que  ser&aacute; responsable del abasto, suficiencia, calidad, cantidad o estado de la misma.</span></p>
    <p style="margin-top:0.35pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:15.05pt; margin-bottom:0pt; text-indent:-10.1pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">4.</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;</span><span style="font-family:Arial;"> DE LOS&nbsp;</span><span style="font-family:Arial; letter-spacing:-0.2pt;">DATOS</span><span style="font-family:Arial; letter-spacing:-0.05pt;">&nbsp;</span><span style="font-family:Arial;">PERSONALES</span></h1>
</div>
<p><br style="page-break-before:always; clear:both; mso-break-type:section-break;"></p>
<div>
    <p style="margin:3.2pt 10.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;"> Datos Personales proporcionados a Blood Bank son usados para  siguientes finalidades, derivadas de  relaci&oacute;n entre el  de  y Blood Bank originada por el inter&eacute;s del titular en ser de los servicios de Blood Bank:</span></p>
    <p style="margin:3.2pt 10.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 4.9pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;"> manera adicional, utilizaremos su informaci&oacute;n personal para las siguientes&nbsp;</span><strong><span style="font-family:Arial;">finalidades secundarias&nbsp;</span></strong><span style="font-family:Arial;">que   indispensables para  fines de Blood Bank, pero que nos permiten y facilitan brindarle  mejor atenci&oacute;n:</span></p>
    <p style="margin-top:0pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-18.05pt; text-align:justify; line-height:10.75pt; widows:0; orphans:0;"><span style="font-family:Arial; font-size:9pt; letter-spacing:-0.05pt;">●</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; font-size:9pt; vertical-align:0.5pt;"> la calidad de los eventos que realizamos</span></p>
    <p style="margin-top:0.6pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-18.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">●</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; vertical-align:0.5pt;">Enviar boletines</span><span style="font-family:Arial; letter-spacing:-0.05pt; vertical-align:0.5pt;">&nbsp;</span><span style="font-family:Arial; vertical-align:0.5pt;">electr&oacute;nicos</span></p>
    <p style="margin-top:0.6pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-18.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">●</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; vertical-align:0.5pt;"> la mercadotecnia o publicidad</span></p>
    <p style="margin:0.6pt 4.9pt 0pt 41.05pt; text-indent:-18pt; text-align:justify; line-height:106%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">●</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; vertical-align:0.5pt;">Elaborar y programas  las necesidades en cuestiones de donaci&oacute;n de</span><span style="font-family:Arial;">&nbsp;sangre</span></p>
    <p style="margin:3.2pt 10.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0.05pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">PRIMARIAS</span></h1>
    <p style="margin-top:1.1pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-36.05pt; text-align:justify; widows:0; orphans:0; font-size:11pt;"><span style="font-family:Arial; font-size:9pt; letter-spacing:-0.5pt;">&bull;</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial; font-size:9pt;">Llevar  regist</span><a href="http://www.blooders.org/" style="text-decoration:none;"><span style="font-family:Arial; font-size:9pt; color:#000000;"> de los usuarios  sitio</span></a><span style="font-family:Arial; font-size:9pt;">&nbsp;[&hellip;]</span></p>
    <p style="margin-top:1.1pt; margin-left:41.05pt; margin-bottom:0pt; text-indent:-36.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.5pt;">&bull;</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">El servicio gratuito&nbsp;</span></p>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">SECUNDARIAS</span></h1>
    <p style="margin:1.1pt 10.05pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.5pt;">&bull;</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Realizar campa&ntilde redes sociales con el finde la donaci&oacute;n o altruista.&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">5.- LIMITACIONES DEL USO Y DIVULGACION DE LOS DATOS</span></h1>
    <p style="margin:1.1pt 6.7pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">Los Datos Personales  son proporcionados a  Bank por medios legales o leg&iacute; son tratados de confidencial y apropiada. Bajo  t&eacute;rminos del art&iacute;culo 36 de Ley, Blood Bank transferir&aacute; los Datos Personales en los casos: 1) para con obligaciones legales existentes; 2) para   orden legal o judicial; y 3) Los Datos Personales ser&aacute;n a terceros que brinden de soporte, atenci&oacute;n y gesti&oacute;n hospitalaria para coordinar, gestionar y los servicios brindados por  Bank en beneficio de los titulares, derivados del inter&eacute;s de los titulares en ser usuarios de dichos servicios. momento el titular podr&aacute; oponerse a que sus datos personales  transferidos, comunic&aacute;ndose con Blood Bank a trav&eacute;s del Correo Electr&oacute;nico. En de que no se oponga, se entender&aacute; que titular permite transferir  datos en los t&eacute;  descritos.  datos personales no ser&aacute;n transferidos fuera los  antes mencionados.</span></p>
    <p style="margin-top:0.15pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 8.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">Tanto el titular de Datos Personales como otra persona que tenga acceso a informaci&oacute;n relacionada  este Aviso, quedan obligados a no revelarla ni hacer mal uso de la misma, o en caso contrario ser&aacute;n de conformidad con  leyes.</span></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0.35pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">6.-  PARA  DERECHOS DEL DE LOS DATOS PERSONALES.</span></h1>
    <p style="margin:1.1pt 4.75pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;"> titular de la informaci&oacute;n personal podr&aacute; solicitar a Blood Bank,  cualquier momento, el acceso, rectificaci&oacute;n, cancelaci&oacute;n u oposici&oacute;n de derechos de sus Datos Personales. Para tal fin, el titular de los Datos deber&aacute; presentar  solicitud por escrito y/o Electr&oacute;nico, dirigida al de Datos Personales,  contendr&aacute; como m&iacute;nimo la siguiente informaci&oacute;n:</span></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-left:54.05pt; margin-bottom:0pt; text-indent:-13.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">a)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;"> nombre del titular y domicilio, u otro medio id&oacute;neo para comunicarle la respuesta a su</span><span style="font-family:Arial; letter-spacing:-0.1pt;">&nbsp;</span><span style="font-family:Arial;">solicitud</span></p>
    <p style="margin-top:1.1pt; margin-left:54.05pt; margin-bottom:0pt; text-indent:-13.05pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">b)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">Los documentos que acrediten identidad o, en caso, la representaci&oacute;n legal del</span><span style="font-family:Arial; letter-spacing:-0.1pt;">&nbsp;</span><span style="font-family:Arial;">titular</span></p>
    <p style="margin:1.15pt 30.1pt 0pt 53.55pt; text-indent:-12.55pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">c)</span><span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;</span><span style="font-family:Arial;">La descripci&oacute;n clara y precisa de los Datos Personales respecto de los que se busca ejercer de los derechos antes</span><span style="font-family:Arial; letter-spacing:-0.55pt;">&nbsp;</span><span style="font-family:Arial;">mencionados</span></p>
    <p style="margin:0pt 28.6pt 0pt 51.05pt; text-indent:-10.05pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial; letter-spacing:-0.05pt;">d)</span><span style="font:7pt 'Times New Roman';">&nbsp;</span><span style="font-family:Arial;">Cualquier otro o documento que facilite la localizaci&oacute;n los Datos Personales,&nbsp;</span><span style="font-family:Arial; letter-spacing:-0.3pt;">as&iacute;&nbsp;</span><span style="font-family:Arial;"> cualquier otro documento requerido por la regulaci&oacute;n actual en el momento de presentar solicitud</span></p>
</div>
<p><br style="page-break-before:always; clear:both; mso-break-type:section-break;"></p>
<div>
    <p style="margin:3.2pt 24.25pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;"> titular de la informaci&oacute;n podr&aacute; obtener m&aacute;s informaci&oacute;n acerca del  su solicitud y  plazos respuesta de  misma mediante solicitud por escrito al Domicilio y/o al Correo Electr&oacute;nico.</span></p>
    <p style="margin-top:0.45pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">7.- REVOCACION</span></h1>
    <p style="margin:1.1pt 5pt 0pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">El titular de la informaci&oacute;n personal podr&aacute; revocar el presente consentimiento para el manejo  Personales o bien su uso o divulgaci&oacute;n en momento, ya sea para la totalidad de las finalidades contenidas en presente aviso, o s&oacute;lo las finalidades secundarias antes se&ntilde;aladas, as&iacute;&nbsp;</span><span style="font-family:Arial; letter-spacing:-0.2pt;">como&nbsp;</span><span style="font-family:Arial;">* las trasferencias de sus datos personales. Para tal fin, deber&aacute; enviar una** escrita al Domicilio o bien al Correo Electr&oacute;nico, con atenci&oacute;n al** de Datos Personales. Dicha comunicaci&oacute;n deber&aacute; cumplir con los requisitos mencionados en la secci&oacute;n 5 anterior.</span></p>
    <p style="margin-top:0.3pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0.05pt 24.25pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">El titular la informaci&oacute;n personal podr&aacute; obtener m&aacute;s informaci&oacute;n acerca del estado de su solicitud y los plazos de de la misma, incluyendo aquellas relacionadas  el ejercicio de mediante solicitud  escrito dirigida al Domicilio, y/o al Correo Electr&oacute;nico.</span></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 9.2pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">En caso de que  titular no manifieste que no desea que se traten  datos para las finalidades en el aviso, incluyendo las finalidades secundarias, un plazo de cuatro d&iacute;as h&aacute;biles a de sus datos personales, entender&aacute; que  titular ha otorgado consentimiento para tratarlos conforme a  establecido en el presente aviso de privacidad.</span></p>
    <p style="margin-top:0.4pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <h1 style="margin-top:0pt; margin-left:5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">8.- MODIFICACIONES AL AVISO DE PRIVACIDAD</span></h1>
    <p style="margin-top:0.5pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10.5pt;"><strong><span style="font-family:Arial;">&nbsp;</span></strong></p>
    <p style="margin:0pt 6.75pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;"> Bank se reserva el modificar este Aviso de Privacidad, en cuyo caso lo comunicar&aacute; por medio de un aviso que se colocar&aacute; en los medios habituales (f&iacute;sicos o electr&oacute;nicos) de comunicaci&oacute;n de Blood Bank y en un lugar visible de  instalaciones, o por medio aviso por escrito digital a  Usuarios y otras involucradas.</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:10pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin-top:0.35pt; margin-bottom:0pt; text-align:justify; widows:0; orphans:0; font-size:9.5pt;"><span style="font-family:Arial;">&nbsp;</span></p>
    <p style="margin:0pt 278.9pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">Fecha de creaci&oacute;n: 10 de Julio de 2020 &Uacute;ltima actualizaci&oacute;n: 15 de Julio  2020</span></p>
    <p style="margin:0pt 278.9pt 0pt 5pt; text-align:justify; line-height:111%; widows:0; orphans:0; font-size:9pt;"><span style="font-family:Arial;">&nbsp;</span></p>
</div>
</div>
</template>

